#!/usr/bin/env bash

if ./gradlew --quiet installDist; then
  ./build/install/GithubAPI/bin/GithubAPI "$@"
else
  echo "Gradle task failed. Please check your files for any errors and run 'gradle build' followed by './gradlew installDist' and try again" >&2
fi

